import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        
        <footer className="common-footer">
          <div className="footer-content">
            <div className="footer-item">
              <span className="icon">✉️</span>
              <a href="mailto:service.desk@novalytixtechservices.com">service.desk@novalytixtechservices.com</a>
            </div>
            <div className="footer-item">
              <span className="icon">📞</span>
              <a href="tel:+919005333587">+91 90053 33587</a>
            </div>
            <div className="footer-item">
              <span className="icon">📞</span>
              <a href="tel:+919415480154">+91 94154 80154</a>
            </div>
            <div className="footer-separator">|</div>
            <div className="footer-copyright">
              © 2026 - Powered by NOVALYTIX TECHNOLOGY SERVICES. ALL RIGHTS RESERVED
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
